# Generated by Django 3.2.5 on 2022-03-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entmt_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_star', models.IntegerField(default=0)),
                ('mc_content', models.CharField(max_length=100)),
                ('mc_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mgenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Scomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_star', models.IntegerField(default=0)),
                ('sc_content', models.CharField(max_length=255)),
                ('sc_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sgenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entmt_info.genres')),
                ('sg_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entmt_info.series')),
            ],
        ),
    ]
