# Generated by Django 3.2.5 on 2022-03-07 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entmt_info', '0001_initial'),
        ('entmt_manage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scomment',
            name='sc_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scomment',
            name='sc_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entmt_info.series'),
        ),
        migrations.AddField(
            model_name='mgenres',
            name='mg_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entmt_info.genres'),
        ),
        migrations.AddField(
            model_name='mgenres',
            name='mg_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entmt_info.movies'),
        ),
        migrations.AddField(
            model_name='mcomment',
            name='mc_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcomment',
            name='mc_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entmt_info.movies'),
        ),
    ]
