# Generated by Django 3.2.5 on 2022-03-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entmt_manage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcomment',
            name='mc_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='scomment',
            name='sc_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mcomment',
            name='mc_star',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scomment',
            name='sc_star',
            field=models.FloatField(),
        ),
    ]
